version: "3"
services:
    routing:
        image: 172.17.0.1:5000/babeld #dm4tze/babeld/dev
        privileged: true
        network_mode: "host"
        container_name: babeld
    
    #transmission:
        #image: 172.17.0.1:5000/transmission
        #restart: unless-stopped
        #privileged: true
        #network_mode: "host"
        #container_name: transmission
        #environment:
            #- PUID=1000
            #- PGID=1000
            #- TZ=Europe/London
        #ports:
            #- 9091:9091 #WebUI
            #- 51413:51413 #Torrent Port TCP
            #- 51413:51413/udp #Torrent Port UDP
        #volumes:
          #- /config:/config
          #- /downloads:/downloads
          #- /watch:/watch

    tracker:
        image: 172.17.0.1:5000/opentracker-docker
        container_name: opentracker
        network_mode: "host"
        ports:
            - 6969:6969 #Torrent Port TCP
            - 6969:6969/udp #Torrent Port UDP
        #volumes: 
            #-etc/opentracker-docker/:etc/opentracker-docker
            #- opentracker-docker/opentracker.conf:opentracker-docker/opentracker.conf
            #- opentracker-docker/whitelist.txt:opentracker-docker/whitelist.conf
            #- opentracker-docker/blacklist.txt:opentracker-docker/blacklist.conf
        restart: unless-stopped

    backend:
        image: 172.17.0.1:5000/registry
        container_name: registry
        privileged: true
        network_mode: "host"
        restart: always
        ports:
            - 5000:5000
            
volumes:
    dbdata: